export interface Lead {
  id: string;
  name: string;
  title: string;
  company: string;
  industry: string;
  companySize: string;
  country: string;
  email: string;
}

export const sampleLeads: Lead[] = [
  { id: "1", name: "Sarah Chen", title: "CEO", company: "NovaTech Solutions", industry: "Technology", companySize: "51-200", country: "United States", email: "sarah@novatech.io" },
  { id: "2", name: "James Mitchell", title: "CTO", company: "CloudPeak Systems", industry: "Technology", companySize: "201-1000", country: "United States", email: "james@cloudpeak.com" },
  { id: "3", name: "Emily Dawson", title: "VP Marketing", company: "BrightLeaf Media", industry: "Marketing", companySize: "11-50", country: "United Kingdom", email: "emily@brightleaf.co.uk" },
  { id: "4", name: "Michael Torres", title: "Founder", company: "FinEdge Capital", industry: "Finance", companySize: "1-10", country: "United States", email: "michael@finedge.com" },
  { id: "5", name: "Rachel Kim", title: "Head of Sales", company: "MedConnect Health", industry: "Healthcare", companySize: "201-1000", country: "Canada", email: "rachel@medconnect.ca" },
  { id: "6", name: "David Okafor", title: "CMO", company: "UrbanNest Realty", industry: "Real Estate", companySize: "11-50", country: "United States", email: "david@urbannest.com" },
  { id: "7", name: "Lisa Yamamoto", title: "Director of Engineering", company: "QuantumByte AI", industry: "Technology", companySize: "51-200", country: "United States", email: "lisa@quantumbyte.ai" },
  { id: "8", name: "Tom Richards", title: "CEO", company: "SwiftCart Commerce", industry: "E-commerce", companySize: "11-50", country: "Australia", email: "tom@swiftcart.au" },
  { id: "9", name: "Priya Sharma", title: "Product Manager", company: "EduPath Learning", industry: "Education", companySize: "51-200", country: "India", email: "priya@edupath.in" },
  { id: "10", name: "Alex Petrov", title: "COO", company: "LexPoint Legal", industry: "Legal", companySize: "11-50", country: "United States", email: "alex@lexpoint.com" },
  { id: "11", name: "Maria Gonzalez", title: "Founder", company: "GrowthForge Agency", industry: "Marketing", companySize: "1-10", country: "United States", email: "maria@growthforge.co" },
  { id: "12", name: "Daniel Weber", title: "CTO", company: "DataStream GmbH", industry: "Technology", companySize: "201-1000", country: "Germany", email: "daniel@datastream.de" },
  { id: "13", name: "Sophie Martin", title: "VP Marketing", company: "VitalCare Clinics", industry: "Healthcare", companySize: "51-200", country: "United Kingdom", email: "sophie@vitalcare.co.uk" },
  { id: "14", name: "Chris Nguyen", title: "Head of Sales", company: "PropVista Homes", industry: "Real Estate", companySize: "51-200", country: "United States", email: "chris@propvista.com" },
  { id: "15", name: "Olivia Brown", title: "CEO", company: "PulseMetric Analytics", industry: "Technology", companySize: "11-50", country: "Canada", email: "olivia@pulsemetric.ca" },
  { id: "16", name: "Hassan Ali", title: "Founder", company: "FinSmart Advisory", industry: "Finance", companySize: "1-10", country: "United Kingdom", email: "hassan@finsmart.co.uk" },
  { id: "17", name: "Jennifer Lee", title: "CMO", company: "StyleHive Boutique", industry: "E-commerce", companySize: "11-50", country: "United States", email: "jennifer@stylehive.com" },
  { id: "18", name: "Mark Anderson", title: "Director of Engineering", company: "CyberShield Security", industry: "Technology", companySize: "201-1000", country: "United States", email: "mark@cybershield.io" },
  { id: "19", name: "Anna Kowalski", title: "Product Manager", company: "LearnLoop EdTech", industry: "Education", companySize: "11-50", country: "Germany", email: "anna@learnloop.de" },
  { id: "20", name: "Robert Clarke", title: "CEO", company: "TrustBridge Consulting", industry: "Consulting", companySize: "51-200", country: "Australia", email: "robert@trustbridge.au" },
  { id: "21", name: "Anika Patel", title: "VP Marketing", company: "CloudNine SaaS", industry: "Technology", companySize: "51-200", country: "India", email: "anika@cloudnine.in" },
  { id: "22", name: "Ben Harper", title: "Head of Sales", company: "FreshCart Delivery", industry: "E-commerce", companySize: "201-1000", country: "United States", email: "ben@freshcart.com" },
  { id: "23", name: "Laura Fischer", title: "COO", company: "MedPrime Labs", industry: "Healthcare", companySize: "1000+", country: "Germany", email: "laura@medprime.de" },
  { id: "24", name: "Kevin O'Brien", title: "Founder", company: "CodeCraft Studios", industry: "Technology", companySize: "1-10", country: "United States", email: "kevin@codecraft.dev" },
  { id: "25", name: "Natalie Cruz", title: "CMO", company: "Elevate Ventures", industry: "Consulting", companySize: "11-50", country: "United States", email: "natalie@elevatevc.com" },
  { id: "26", name: "Ryan Thompson", title: "CTO", company: "BlockForge Labs", industry: "Technology", companySize: "11-50", country: "United States", email: "ryan@blockforge.io" },
  { id: "27", name: "Chloe Edwards", title: "CEO", company: "BrightPath Education", industry: "Education", companySize: "51-200", country: "United Kingdom", email: "chloe@brightpath.co.uk" },
  { id: "28", name: "Steve Park", title: "Director of Engineering", company: "AutoFlow Robotics", industry: "Technology", companySize: "201-1000", country: "United States", email: "steve@autoflow.com" },
  { id: "29", name: "Diana Reyes", title: "Head of Sales", company: "LuxeHome Realty", industry: "Real Estate", companySize: "11-50", country: "United States", email: "diana@luxehome.com" },
  { id: "30", name: "Marcus Johnson", title: "VP Marketing", company: "PayFlow Financial", industry: "Finance", companySize: "51-200", country: "United States", email: "marcus@payflow.com" },
  { id: "31", name: "Yuki Tanaka", title: "Product Manager", company: "PixelForge Design", industry: "Technology", companySize: "11-50", country: "United States", email: "yuki@pixelforge.co" },
  { id: "32", name: "Andrew Scott", title: "CEO", company: "GreenLeaf AgriTech", industry: "Technology", companySize: "51-200", country: "Australia", email: "andrew@greenleaf.au" },
  { id: "33", name: "Isabel Santos", title: "Founder", company: "PulsePoint Marketing", industry: "Marketing", companySize: "1-10", country: "United States", email: "isabel@pulsepoint.co" },
  { id: "34", name: "Nathan Wright", title: "COO", company: "HealthBridge Pharma", industry: "Healthcare", companySize: "1000+", country: "United States", email: "nathan@healthbridge.com" },
  { id: "35", name: "Karen Liu", title: "CTO", company: "SmartHive Analytics", industry: "Technology", companySize: "51-200", country: "Canada", email: "karen@smarthive.ca" },
  { id: "36", name: "Paul Bennett", title: "Head of Sales", company: "TradeVista Markets", industry: "Finance", companySize: "201-1000", country: "United Kingdom", email: "paul@tradevista.co.uk" },
  { id: "37", name: "Zara Hussain", title: "CMO", company: "ShopStream Online", industry: "E-commerce", companySize: "51-200", country: "United Kingdom", email: "zara@shopstream.co.uk" },
  { id: "38", name: "Greg Foster", title: "CEO", company: "Summit Legal Group", industry: "Legal", companySize: "51-200", country: "United States", email: "greg@summitlegal.com" },
  { id: "39", name: "Monica Bauer", title: "VP Marketing", company: "NexGen Consulting", industry: "Consulting", companySize: "201-1000", country: "Germany", email: "monica@nexgen.de" },
  { id: "40", name: "Jason Kim", title: "Director of Engineering", company: "Orbital Cloud", industry: "Technology", companySize: "201-1000", country: "United States", email: "jason@orbitalcloud.com" },
  { id: "41", name: "Tanya Volkov", title: "Founder", company: "ClearView Analytics", industry: "Technology", companySize: "1-10", country: "Canada", email: "tanya@clearview.ca" },
  { id: "42", name: "Derek Hall", title: "CEO", company: "PrimeHealth Systems", industry: "Healthcare", companySize: "201-1000", country: "United States", email: "derek@primehealth.com" },
  { id: "43", name: "Samantha Wood", title: "Head of Sales", company: "AdVantage Media", industry: "Marketing", companySize: "51-200", country: "United States", email: "samantha@advantagemedia.com" },
  { id: "44", name: "Leo Fernandez", title: "Product Manager", company: "FinTrack Pro", industry: "Finance", companySize: "11-50", country: "United States", email: "leo@fintrack.io" },
  { id: "45", name: "Amy Richardson", title: "COO", company: "HomeBase Realty", industry: "Real Estate", companySize: "201-1000", country: "Australia", email: "amy@homebase.au" },
  { id: "46", name: "Raj Mehta", title: "CTO", company: "LearnWise Academy", industry: "Education", companySize: "51-200", country: "India", email: "raj@learnwise.in" },
  { id: "47", name: "Stephanie Ross", title: "Founder", company: "LegalEase Tech", industry: "Legal", companySize: "1-10", country: "United States", email: "stephanie@legalease.io" },
  { id: "48", name: "Carlos Mendez", title: "CMO", company: "FlowState Digital", industry: "Marketing", companySize: "11-50", country: "United States", email: "carlos@flowstate.co" },
  { id: "49", name: "Helen Zhang", title: "VP Marketing", company: "NeuralNet Labs", industry: "Technology", companySize: "51-200", country: "United States", email: "helen@neuralnet.ai" },
  { id: "50", name: "Tim O'Connor", title: "CEO", company: "RapidShip Logistics", industry: "E-commerce", companySize: "201-1000", country: "United Kingdom", email: "tim@rapidship.co.uk" },
  { id: "51", name: "Nina Johansson", title: "Head of Sales", company: "StratEdge Consulting", industry: "Consulting", companySize: "51-200", country: "Germany", email: "nina@stratedge.de" },
  { id: "52", name: "Brian Cooper", title: "Director of Engineering", company: "VaultSecure", industry: "Technology", companySize: "51-200", country: "United States", email: "brian@vaultsecure.com" },
  { id: "53", name: "Megan Taylor", title: "Founder", company: "WellPath Health", industry: "Healthcare", companySize: "1-10", country: "United States", email: "megan@wellpath.co" },
  { id: "54", name: "Oscar Nilsson", title: "CTO", company: "PayNova Financial", industry: "Finance", companySize: "201-1000", country: "Germany", email: "oscar@paynova.de" },
  { id: "55", name: "Julia Morris", title: "CEO", company: "BrightSpark Agency", industry: "Marketing", companySize: "11-50", country: "Australia", email: "julia@brightspark.au" },
  { id: "56", name: "Arjun Reddy", title: "Product Manager", company: "DocuFlow Systems", industry: "Technology", companySize: "51-200", country: "India", email: "arjun@docuflow.in" },
  { id: "57", name: "Kate Wilson", title: "VP Marketing", company: "Pinnacle Homes", industry: "Real Estate", companySize: "51-200", country: "United States", email: "kate@pinnaclehomes.com" },
  { id: "58", name: "Frank Mueller", title: "COO", company: "EduForce Global", industry: "Education", companySize: "201-1000", country: "Germany", email: "frank@eduforce.de" },
  { id: "59", name: "Vanessa Chang", title: "Head of Sales", company: "CartBoss E-commerce", industry: "E-commerce", companySize: "11-50", country: "Canada", email: "vanessa@cartboss.ca" },
  { id: "60", name: "Patrick Kelly", title: "Founder", company: "LawBridge Partners", industry: "Legal", companySize: "11-50", country: "United States", email: "patrick@lawbridge.com" },
  { id: "61", name: "Rebecca Stone", title: "CMO", company: "InsightIQ Data", industry: "Technology", companySize: "51-200", country: "United States", email: "rebecca@insightiq.com" },
  { id: "62", name: "Simon Becker", title: "CEO", company: "MedTech Innovations", industry: "Healthcare", companySize: "51-200", country: "Germany", email: "simon@medtechinno.de" },
  { id: "63", name: "Amanda Hayes", title: "Director of Engineering", company: "ScaleUp Cloud", industry: "Technology", companySize: "201-1000", country: "United States", email: "amanda@scaleupcloud.com" },
  { id: "64", name: "Victor Lam", title: "Head of Sales", company: "WealthPoint Advisory", industry: "Finance", companySize: "11-50", country: "Canada", email: "victor@wealthpoint.ca" },
  { id: "65", name: "Nicole Adams", title: "VP Marketing", company: "AdReach Digital", industry: "Marketing", companySize: "51-200", country: "United States", email: "nicole@adreach.co" },
  { id: "66", name: "Ian Douglas", title: "CTO", company: "PropertyPro Tech", industry: "Real Estate", companySize: "11-50", country: "United Kingdom", email: "ian@propertypro.co.uk" },
  { id: "67", name: "Christine Park", title: "Founder", company: "SkillBridge Learning", industry: "Education", companySize: "1-10", country: "United States", email: "christine@skillbridge.co" },
  { id: "68", name: "Tyler James", title: "CEO", company: "RetailFlow Pro", industry: "E-commerce", companySize: "51-200", country: "United States", email: "tyler@retailflow.com" },
  { id: "69", name: "Sandra Costa", title: "COO", company: "Apex Consulting Group", industry: "Consulting", companySize: "201-1000", country: "United States", email: "sandra@apexcg.com" },
  { id: "70", name: "Liam Murphy", title: "Product Manager", company: "SecureVault Tech", industry: "Technology", companySize: "51-200", country: "United Kingdom", email: "liam@securevault.co.uk" },
  { id: "71", name: "Eva Lindgren", title: "Founder", company: "GreenMed Wellness", industry: "Healthcare", companySize: "1-10", country: "Germany", email: "eva@greenmed.de" },
  { id: "72", name: "Jake Robinson", title: "Head of Sales", company: "AccelPay Systems", industry: "Finance", companySize: "51-200", country: "Australia", email: "jake@accelpay.au" },
  { id: "73", name: "Deepa Nair", title: "CMO", company: "SignalBoost Marketing", industry: "Marketing", companySize: "11-50", country: "India", email: "deepa@signalboost.in" },
  { id: "74", name: "Carl Stevens", title: "CEO", company: "JurisCore Legal", industry: "Legal", companySize: "51-200", country: "United States", email: "carl@juriscore.com" },
  { id: "75", name: "Michelle Long", title: "VP Marketing", company: "TechPulse Ventures", industry: "Technology", companySize: "201-1000", country: "United States", email: "michelle@techpulse.io" },
  { id: "76", name: "Omar Khoury", title: "Director of Engineering", company: "BuildRight Realty", industry: "Real Estate", companySize: "51-200", country: "United States", email: "omar@buildright.com" },
  { id: "77", name: "Fiona Campbell", title: "CTO", company: "ClassForward EdTech", industry: "Education", companySize: "51-200", country: "United Kingdom", email: "fiona@classforward.co.uk" },
  { id: "78", name: "Aaron White", title: "Founder", company: "DropZone Commerce", industry: "E-commerce", companySize: "1-10", country: "United States", email: "aaron@dropzone.co" },
  { id: "79", name: "Catherine Zhao", title: "COO", company: "Mosaic Consulting", industry: "Consulting", companySize: "51-200", country: "Canada", email: "catherine@mosaic.ca" },
  { id: "80", name: "Peter Hoffman", title: "CEO", company: "CoreMed Diagnostics", industry: "Healthcare", companySize: "1000+", country: "Germany", email: "peter@coremed.de" },
  { id: "81", name: "Sarah Walker", title: "Head of Sales", company: "PixelPerfect Agency", industry: "Marketing", companySize: "11-50", country: "Australia", email: "sarah@pixelperfect.au" },
  { id: "82", name: "Eric Johansson", title: "Product Manager", company: "CreditWise Finance", industry: "Finance", companySize: "201-1000", country: "United Kingdom", email: "eric@creditwise.co.uk" },
  { id: "83", name: "Wendy Price", title: "VP Marketing", company: "CloudBase Systems", industry: "Technology", companySize: "51-200", country: "United States", email: "wendy@cloudbase.io" },
  { id: "84", name: "Nate Collins", title: "Founder", company: "ContractFlow Legal", industry: "Legal", companySize: "1-10", country: "United States", email: "nate@contractflow.com" },
  { id: "85", name: "Rosa Gutierrez", title: "CMO", company: "NestFinder Homes", industry: "Real Estate", companySize: "51-200", country: "United States", email: "rosa@nestfinder.com" },
  { id: "86", name: "Henry Shaw", title: "CEO", company: "LevelUp Tutoring", industry: "Education", companySize: "11-50", country: "United States", email: "henry@leveluptutoring.com" },
  { id: "87", name: "Lena Braun", title: "CTO", company: "ShopSphere Online", industry: "E-commerce", companySize: "201-1000", country: "Germany", email: "lena@shopsphere.de" },
  { id: "88", name: "Victor Chan", title: "Director of Engineering", company: "Apex Analytics", industry: "Technology", companySize: "51-200", country: "Canada", email: "victor@apexanalytics.ca" },
  { id: "89", name: "Alison Reed", title: "Head of Sales", company: "PeakPerform Consulting", industry: "Consulting", companySize: "11-50", country: "United States", email: "alison@peakperform.co" },
  { id: "90", name: "Rahul Gupta", title: "Founder", company: "MedAI Solutions", industry: "Healthcare", companySize: "1-10", country: "India", email: "rahul@medai.in" },
  { id: "91", name: "Tracy Bell", title: "VP Marketing", company: "MoneyPath Finance", industry: "Finance", companySize: "51-200", country: "United States", email: "tracy@moneypath.com" },
  { id: "92", name: "Danny Fox", title: "CEO", company: "LaunchPad Marketing", industry: "Marketing", companySize: "11-50", country: "United States", email: "danny@launchpadmktg.com" },
  { id: "93", name: "Ingrid Svensson", title: "COO", company: "DataBridge Tech", industry: "Technology", companySize: "201-1000", country: "Germany", email: "ingrid@databridge.de" },
  { id: "94", name: "Tony Russo", title: "Head of Sales", company: "KeyStone Realty", industry: "Real Estate", companySize: "201-1000", country: "United States", email: "tony@keystonerealty.com" },
  { id: "95", name: "Grace Kim", title: "Product Manager", company: "JusticeLink Legal", industry: "Legal", companySize: "51-200", country: "United States", email: "grace@justicelink.com" },
  { id: "96", name: "Matt Simmons", title: "CTO", company: "CartGenius", industry: "E-commerce", companySize: "11-50", country: "United Kingdom", email: "matt@cartgenius.co.uk" },
  { id: "97", name: "Pooja Iyer", title: "Founder", company: "CampusWise EdTech", industry: "Education", companySize: "1-10", country: "India", email: "pooja@campuswise.in" },
  { id: "98", name: "George Palmer", title: "CEO", company: "Vertex Consulting", industry: "Consulting", companySize: "51-200", country: "United States", email: "george@vertexcg.com" },
  { id: "99", name: "Bianca Moretti", title: "CMO", company: "CarePoint Health", industry: "Healthcare", companySize: "201-1000", country: "United Kingdom", email: "bianca@carepoint.co.uk" },
  { id: "100", name: "Will Turner", title: "Director of Engineering", company: "LedgerPro Finance", industry: "Finance", companySize: "1000+", country: "United States", email: "will@ledgerpro.com" },
];

export function maskEmail(email: string): string {
  const [local, domain] = email.split("@");
  if (!local || !domain) return "***@***.com";
  return `${local[0]}***@${domain}`;
}
